server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://47.109.55.137:3306/flowable?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password: hetao   # 你的密码
    driver-class-name: com.mysql.cj.jdbc.Driver
flowable:
  database-schema-update: true   # 自动建表
  async-executor-activate: false
